<?php

namespace App\Exports;

use App\Services\Reports\Report;
use Maatwebsite\Excel\Concerns\FromArray;
use Maatwebsite\Excel\Concerns\FromGenerator;
use Maatwebsite\Excel\Concerns\WithHeadings;
use Maatwebsite\Excel\Concerns\WithMultipleSheets;
use Maatwebsite\Excel\Concerns\WithTitle;

/**
 * Excel version of any report: rows (streamed from Report::rows), summary
 * sections, and a sheet describing the report and its filters.
 */
class ReportExport implements WithMultipleSheets
{
    public function __construct(
        public readonly Report $report,
        public readonly array $filters,
        public readonly array $context,
    ) {}

    public function sheets(): array
    {
        $sheets = [];

        if ($this->report->hasRows($this->filters)) {
            $sheets[] = new class($this->report, $this->filters) implements FromGenerator, WithHeadings, WithTitle
            {
                public function __construct(private Report $report, private array $filters) {}

                public function generator(): \Generator
                {
                    $keys = array_keys($this->report->columns($this->filters));

                    foreach ($this->report->rows($this->filters) as $row) {
                        yield array_map(fn ($key) => $row[$key] ?? null, $keys);
                    }
                }

                public function headings(): array
                {
                    return array_values($this->report->columns($this->filters));
                }

                public function title(): string
                {
                    return 'Data';
                }
            };
        }

        $summary = $this->report->summary($this->filters);

        if ($summary !== []) {
            $rows = [];

            foreach ($summary as $section) {
                $rows[] = [$section['title']];
                $rows[] = $section['columns'];
                array_push($rows, ...$section['rows']);
                $rows[] = [];
            }

            $sheets[] = new class($rows) implements FromArray, WithTitle
            {
                public function __construct(private array $rows) {}

                public function array(): array
                {
                    return $this->rows;
                }

                public function title(): string
                {
                    return 'Summary';
                }
            };
        }

        $info = [
            ['Report', $this->report->title()],
            ['Organization', $this->context['organization']],
            ['Generated', $this->context['generatedAt']],
            ['Generated by', $this->context['generatedBy']],
            [],
            ['Filters'],
        ];

        foreach ($this->report->describeFilters($this->filters) as $label => $value) {
            $info[] = [$label, $value];
        }

        foreach ($this->report->notes() as $note) {
            $info[] = ['Note', $note];
        }

        $sheets[] = new class($info) implements FromArray, WithTitle
        {
            public function __construct(private array $rows) {}

            public function array(): array
            {
                return $this->rows;
            }

            public function title(): string
            {
                return 'Report Info';
            }
        };

        return $sheets;
    }
}
